# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DuoRenKaiFa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DuoRenKaiFa

    pod 'AFNetworking'
  target 'DuoRenKaiFaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DuoRenKaiFaUITests' do
    # Pods for testing
  end

end
